src/Itgeak.WEB/Models/ErrorViewModel.cs
namespace Itgeak.WEB.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/Itgeak.WEB/Areas/Admin/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Itgeak.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashBoardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Itgeak.WEB/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Itgeak.WEB.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Itgeak.WEB/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Itgeak.WEB.Models;

namespace Itgeak.WEB.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }
    public IActionResult All()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Itgeak.WEB/Areas/Admin/Views/DashBoard/Index.cshtml
@{

}

<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

<div class="row">
    <div class="col-xl-8 col-lg-7">
        <!-- Area Chart -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
            </div>
            <div class="card-body">
                <div class="chart-area">
                    <canvas id="myAreaChart"></canvas>
                </div>
                <hr>
                Styling for the area chart can be found in the
                <code>/js/demo/chart-area-demo.js</code> file.
            </div>
        </div>
    </div>
</div>

src/Itgeak.WEB/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        @ViewBag.Title
    </title>

    <!-- Custom fonts for this template-->
    <link href="~/lib/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/admin/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">ItGeek Admin</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" asp-controller="DashBoard" asp-action="Index">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Главная</span>
        </a>
    </li>
    <!-- Divider -->
        <hr class="sidebar-divider my-0">
    <!-- Heading -->
        <div class="sidebar-heading">
            Контент
        </div>
    <li class="nav-item">
        <a class="nav-link" asp-controller="DashBoard" asp-action="Index">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Главная</span>
        </a>
    </li>
    
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

<!-- Main Content -->
<div id="content">

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
</button>

<!-- Topbar Search -->
<form
    class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
               aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
            </button>
        </div>
    </div>
</form>

<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">
    

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
            <img class="~/img/undraw_profile.svg rounded-circle"
                 src="img/undraw_profile.svg">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
             aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Settings
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Activity Log
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
            </a>
        </div>
    </li>

</ul>

</nav>
<!-- End of Topbar -->

<!-- Begin Page Content -->
<div class="container-fluid">
    @RenderBody()


</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->

<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; ItGeek @DateTime.Now.Year</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

</div>
<!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/jquery-easing/jquery.easing.min.js"></script>
<script src="~/lib/chart.js/Chart.bundle.min.js"></script>


<!-- Custom scripts for all pages-->
<script src="~/js/admin/sb-admin-2.min.js"></script>
<script src="~/js/admin/chart-area-demo.js"></script>

</body>

</html>

src/Itgeak.WEB/Views/Home/About.cshtml
<div class="pattern pattern-cat-header">
    <div class="cat-header header-about">
        <div class="cat-header-block">
            <h1>О сайте ITGEEK.ru</h1>
        </div>
    </div>
</div>

<div class="article-content">
    <div class="container">
        <div class="row">

            <div class="col-md-8">

                <article class="main-article">

                    <div class="article-body">

                        <p>Новую версию телефона показала компания BaoliYota Technology на IV российско-китайском ЭКСПО в Харбине.</p>
                        <p>YotaPhone 3 выпустят в двух версиях: с 64 ГБ и 128 ГБ памяти с возможностью расширения. Аппараты будут стоить $350 и $450 соотвественно. Кроме того, смартфон получит два независимых экрана, один из которых создан на основе технологии электронных чернил. В продажу устройство поступит в конце текущего года.</p>
                        <p>Предполагается, что YotaPhone 3 будет работать на четырехъядерном процессоре Snadpragon 820, будет иметь 3 или 4 ГБ оперативной памяти (в зависимости от версии) и сможет похвастаться 13-мегапиксельной основной и 5-мегапиксельной фронтальной камерами. Несъемный аккумулятор рассчитан на 3 500 мАч.</p>
                        <p>"Судя по техническим характеристикам, YotaPhone 3 специально упростили, чтобы сделать его дешевле. К концу года, когда он поступит в продажу, это будет морально устаревшее устройство, аналоги которого другие производители выпускали два года назад", - заявил Дмитрий Рябинин, руководитель проекта Hi-Tech Mail.Ru.</p>
                        <p>Далеко-далеко за словесными горами в стране, гласных и согласных живут рыбные тексты. Предупреждал знаках вдали, рекламных, текстами текст курсивных всеми это раз прямо которой первую даль большой дал! Коварный единственное, дороге осталось.</p>
                        <p>Новую версию телефона показала компания BaoliYota Technology на IV российско-китайском ЭКСПО в Харбине.</p>
                        <p>YotaPhone 3 выпустят в двух версиях: с 64 ГБ и 128 ГБ памяти с возможностью расширения. Аппараты будут стоить $350 и $450 соотвественно. Кроме того, смартфон получит два независимых экрана, один из которых создан на основе технологии электронных чернил. В продажу устройство поступит в конце текущего года.</p>
                        <p>Предполагается, что YotaPhone 3 будет работать на четырехъядерном процессоре Snadpragon 820, будет иметь 3 или 4 ГБ оперативной памяти (в зависимости от версии) и сможет похвастаться 13-мегапиксельной основной и 5-мегапиксельной фронтальной камерами. Несъемный аккумулятор рассчитан на 3 500 мАч.</p>
                        <p>"Судя по техническим характеристикам, YotaPhone 3 специально упростили, чтобы сделать его дешевле. К концу года, когда он поступит в продажу, это будет морально устаревшее устройство, аналоги которого другие производители выпускали два года назад", - заявил Дмитрий Рябинин, руководитель проекта Hi-Tech Mail.Ru.</p>
                        <p>YotaPhone 3 выпустят в двух версиях: с 64 ГБ и 128 ГБ памяти с возможностью расширения. Аппараты будут стоить $350 и $450 соотвественно. Кроме того, смартфон получит два независимых экрана, один из которых создан на основе технологии электронных чернил. В продажу устройство поступит в конце текущего года.</p>
                        <p>Предполагается, что YotaPhone 3 будет работать на четырехъядерном процессоре Snadpragon 820, будет иметь 3 или 4 ГБ оперативной памяти (в зависимости от версии) и сможет похвастаться 13-мегапиксельной основной и 5-мегапиксельной фронтальной камерами. Несъемный аккумулятор рассчитан на 3 500 мАч.</p>
                        <p>"Судя по техническим характеристикам, YotaPhone 3 специально упростили, чтобы сделать его дешевле. К концу года, когда он поступит в продажу, это будет морально устаревшее устройство, аналоги которого другие производители выпускали два года назад", - заявил Дмитрий Рябинин, руководитель проекта Hi-Tech Mail.Ru.</p>
                        <p>YotaPhone 3 выпустят в двух версиях: с 64 ГБ и 128 ГБ памяти с возможностью расширения. Аппараты будут стоить $350 и $450 соотвественно. Кроме того, смартфон получит два независимых экрана, один из которых создан на основе технологии электронных чернил. В продажу устройство поступит в конце текущего года.</p>
                        <p>Предполагается, что YotaPhone 3 будет работать на четырехъядерном процессоре Snadpragon 820, будет иметь 3 или 4 ГБ оперативной памяти (в зависимости от версии) и сможет похвастаться 13-мегапиксельной основной и 5-мегапиксельной фронтальной камерами. Несъемный аккумулятор рассчитан на 3 500 мАч.</p>

                    </div>

                </article>

            </div>

            <div class="col-md-4">

                <aside class="main-aside">

                    <div class="aside-box">
                        <img src="img/ad-vertical.jpg" alt="alt" class="img-responsive">
                    </div>

                    <div class="aside-box">

                        <div class="latest-box">

                            <div class="lb-header">Последние статьи:</div>

                            <div class="lb-list">

                                <div class="lb-item">
                                    <a href="#" class="lb-catname">Электроника</a>
                                    <div class="lb-body">
                                        <a class="lb-item-header" href="#">Потрясающие снимки на новый смартфон на Android</a>
                                        <div class="lb-footer">
                                            <div class="item-comments" title="Количество комментариев">
                                                <i class="fa fa-comment"></i><a class="item-comments-count" href="#disqus_thread">26</a>
                                                <span class="date">25/12/2023</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="lb-item">
                                    <a href="#" class="lb-catname">Обзоры</a>
                                    <div class="lb-body">
                                        <a class="lb-item-header" href="#">Золотистый iPhone предыдущего поколения положили на тыкву. Потрясающие снимки на Android.</a>
                                        <div class="lb-footer">
                                            <div class="item-comments" title="Количество комментариев">
                                                <i class="fa fa-comment"></i><a class="item-comments-count" href="#disqus_thread">26</a>
                                                <span class="date">25/12/2023</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="lb-item">
                                    <a href="#" class="lb-catname">Новости IT</a>
                                    <div class="lb-body">
                                        <a class="lb-item-header" href="#">Потрясающие снимки на новый смартфон на Android</a>
                                        <div class="lb-footer">
                                            <div class="item-comments" title="Количество комментариев">
                                                <i class="fa fa-comment"></i><a class="item-comments-count" href="#disqus_thread">26</a>
                                                <span class="date">25/12/2023</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="lb-item">
                                    <a href="#" class="lb-catname">Лайфхаки</a>
                                    <div class="lb-body">
                                        <a class="lb-item-header" href="#">Золотистый iPhone предыдущего поколения положили на тыкву. Потрясающие снимки на Android.</a>
                                        <div class="lb-footer">
                                            <div class="item-comments" title="Количество комментариев">
                                                <i class="fa fa-comment"></i><a class="item-comments-count" href="#disqus_thread">26</a>
                                                <span class="date">25/12/2023</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="lb-item">
                                    <a href="#" class="lb-catname">DIY</a>
                                    <div class="lb-body">
                                        <a class="lb-item-header" href="#">Потрясающие снимки на новый смартфон на Android</a>
                                        <div class="lb-footer">
                                            <div class="item-comments" title="Количество комментариев">
                                                <i class="fa fa-comment"></i><a class="item-comments-count" href="#disqus_thread">26</a>
                                                <span class="date">25/12/2023</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>

                    </div>

                    <div class="aside-box">
                        <img src="img/vk-witget.jpg" alt="alt" class="img-responsive">
                    </div>

                    <div class="aside-box">
                        Latest Comments
                    </div>

                </aside>

            </div>

        </div>
    </div>
</div>

src/Itgeak.WEB/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="contaiter">
        <nav class="main-menu footer-menu">
            <ul>
                <li class="active">
                    <a href="#">Электроника</a>
                </li>
                <li>
                    <a href="#">Новости IT</a>
                </li>
                <li>
                    <a href="#">Обзоры</a>
                </li>
                <li>
                    <a href="#">Лайфхаки</a>
                </li>
                <li>
                    <a href="#">DIY</a>
                </li>
                <li>
                    <a href="#">О сайте</a>
                </li>
            </ul>
        </nav>

        <nav class="soc">
            <ul>
                <li>
                    <a href="#">
                        <i class="fa fa-vk"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-facebook"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-odnoklassniki"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-instagram"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-rss"></i>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</footer>
<footer class="bottom-footer">
    <div class="container text-center">
        <div class="footer-copy">
            2018 © <span class="logo-footer logo-litera">ITGEEK.ru</span>
        </div>
        <p>Копирование контента и размещение на других сайтах запрещено.</p>
    </div>
</footer>

src/Itgeak.WEB/Views/Shared/_Header.cshtml
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="logo logo-litera">ITGEEK</a>
            </div>
            <div class="col">
                <div class="mobile-menu-button">
                    <i class="fa fa-bars"></i> Меню
                </div>

                <div class="header__menu">
                    <nav class="main-menu top-menu">
                        <ul>
                            <li class="active">
                                <a asp-controller="Category" asp-action="Index">Электроника</a>
                            </li>
                            <li>
                                <a asp-controller="Category" asp-action="Index">Новости IT</a>
                            </li>
                            <li>
                                <a asp-controller="Category" asp-action="Index">Обзоры</a>
                            </li>
                            <li>
                                <a asp-controller="Category" asp-action="Index">Лайфхаки</a>
                            </li>
                            <li>
                                <a asp-controller="Category" asp-action="Index">DIY</a>
                            </li>
                            <li>
                                <a asp-controller="Home" asp-action="About">О сайте</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-1">
                <div class="search-wrap">
                    <div class="search" title="Поиск по сайту...">
                        <div class="fa fa-search"></div>
                    </div>
                    <div class="search-field">
                        <form action="/search.html" id="cse-search-box">
                            <input type="hidden" name="cx" value="partner-pub-xxx:xxx"/>
                            <input type="hidden" name="cof" value="FORID:10"/>
                            <input type="hidden" name="ie" value="UTF-8"/>
                            <input type="text" name="q" placeholder="Поиск по сайту..."/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

src/Itgeak.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <base href="/"/>
    <meta
        name="description"
        content="Новости электроники, технологий, современных гаджетов, и другая актуальная информация современной IT индустрии"/>

    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"/>

    <!-- Template Basic Images Start -->
    <meta property="og:image" content="path/to/image.jpg"/>
    <link rel="icon" href="img/favicon/favicon.ico"/>
    <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="img/favicon/apple-touch-icon-180x180.png"/>
    <!-- Template Basic Images End -->

    <!-- Custom Browsers Color Start -->
    <meta name="theme-color" content="#202222"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Новости из мира IT</title>
    <link rel="stylesheet" href="~/css/main.min.css" asp-append-version="true"/>
</head>
<body>
@Html.Partial("_Header")

<main role="main">
    @RenderBody()
</main>

@Html.Partial("_Footer")

<script src="~/js/scripts.min.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>